---
title: "Drought"
editor_options: 
  chunk_output_type: console
---

## US Droughts

<https://github.com/rfordatascience/tidytuesday/tree/master/data/2022/2022-06-14>

## setup
```{r}
#..........................load packages.........................
library(tidyverse)
library(ggstream)

#..........................import data...........................
tuesdata <- tidytuesdayR::tt_load('2021-07-20')
drought <- tuesdata$drought
```

## clean data
```{r}
#..........................wrangle data..........................
drought_clean <- drought |>

  # select cols of interest ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add year col ----
  mutate(year = year(date)) |>

  # add drought level conditions names ----
  mutate(drought_lvl_long = factor(drought_lvl,
                            levels = c("D4", "D3", "D2", "D1","D0", "None"),
                            labels = c("Exceptional Drought", "Extreme Drought",
                                       "Severe Drought", "Moderate Drought", "Abnormally Dry", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  select(date, year, state_abb, drought_lvl, drought_lvl_long, area_pct)
 
```

## area plot (CA, total area experiencing drought)
```{r}
drought_clean |> 
  filter(state_abb == "CA",
         drought_lvl != "None") |> 
  group_by(date) |> 
  summarize(total_perc_area_drought = sum(area_pct)) |> 
  ggplot(aes(x = date, y = total_perc_area_drought)) +
  geom_area()
```

## stacked area graph (CA)
See: <https://en.wikipedia.org/wiki/Droughts_in_California>
```{r}
drought_clean |> 
  filter(drought_lvl != "None",
         state_abb == "CA") |> 
  ggplot(drought_states, mapping = aes(x = date, y = area_pct, fill = drought_lvl_long)) +
  geom_area(position = position_stack(reverse = TRUE)) +
  scale_fill_manual(values = c("#853904", "#FF0000", "#FFC100", "#FFD965", "#FFFF00"))
```

## stream graph

## line plot

```{r}
drought_clean |> 
  filter(state_abb == "CA", 
         drought_lvl != "None") |> 
  group_by(date) |> 
  summarize(total_perc_area_drought = sum(area_pct)) |> 
  filter(date >= "2002-07-02" & date <= "2002-09-24") |> 
  ggplot(aes(x = date, y = total_perc_area_drought)) +
  geom_line()
```


## connected scatterplot










---- copied from website repo
```{r}
#| eval: false
#| echo: false
# total drought CA
# TEST <- drought_clean |> 
#   filter(state_abb == "CA",
#          drought_lvl != "None") |> 
#   group_by(date) |> 
#   summarize(total_perc_area_drought = sum(area_pct)) #|> 
#   ggplot(aes(x = date, y = total_perc_area_drought)) +
#   geom_area()
```


```{r}
#| eval: false
#| echo: false

#Midwest: 2011-2012
# month on x-axis, area on y-axis, group = year, color = state_abb

# drought_clean |> 
#   filter(drought_lvl == "D4",
#          #drought_lvl != "None",
#          year != "2021",
#          state_abb == "CA") |>
#   group_by(year, month) |> # , drought_lvl
#   summarize(avg_area = mean(area_pct)) |> 
#   ggplot(aes(x = month, y = avg_area, group = year, color = year)) +
#   geom_line() +
#   #facet_wrap(~drought_lvl) +
#   gghighlight::gghighlight(max(avg_area) > 50) 
# 
# drought_clean |> 
#   filter(drought_lvl == "D1",
#          #drought_lvl != "None",
#          year != "2021",
#          state_abb == "CA") |>
#   group_by(year, month) |> # , drought_lvl
#   summarize(avg_area = mean(area_pct)) |> 
#   ggplot(aes(x = month, y = avg_area, group = year, color = year)) +
#   geom_line() +
#   #facet_wrap(~drought_lvl) +
#   gghighlight::gghighlight(max(avg_area) > 50) 
```


```{r}
# D4 (Exceptional Drought only)
# 
# test2 <- drought_clean |> 
#   group_by(year, month, day, state_abb) |> 
#   summarize(total_perc_area_drought = sum(area_pct))
# 
# # D4
# drought_clean |> 
#   filter(drought_lvl == "D4",
#          year %in% c(2010:2012)) |> 
#   ggplot(aes(x = date, y = area_pct, group = state_abb, color = state_abb)) +
#   geom_line() +
#   gghighlight::gghighlight(max(area_pct) > 75)
```

